splash = false

wallpaper {
  monitor = HDMI-A-1
  path = /home/mt/.config/hypr/wallpapers/SIArch-horizontal.jpg
  fit_mode = fill
}

wallpaper {
  monitor = HDMI-A-2
  path = /home/mt/.config/hypr/wallpapers/SIArch-vertical.jpg
  fit_mode = fill
}
