background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 1.2
    brightness = 0.8
    vibrancy = 0.21
    vibrancy_darkness = 0.0
}

general {
    grace = 2
    hide_cursor = true
    no_fade_in = false
}

input-field {
    monitor =
    size = 320, 55
    outline_thickness = 2

    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true

    outer_color = rgb(151515)
    inner_color = rgb(101010)
    font_color = rgb(ffffff)

    fade_on_empty = false
    rounding = 12

    placeholder_text = <i>Password...</i>

    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(255,255,255,0.9)

    font_size = 72
    font_family = JetBrainsMono Nerd Font

    position = 0, 80
    halign = center
    valign = center
}
